import turtle

my_turtle = turtle.Turtle()
my_turtle = turtle.Screen()
my_turtle = turtle.pencolor("purple")
my_turtle = turtle.shape("turtle")
my_turtle = turtle.forward(50)
my_turtle = turtle.left(90)
my_turtle = turtle.forward(50)
my_turtle = turtle.left(90)
my_turtle = turtle.forward(50)
my_turtle = turtle.left(90)
my_turtle = turtle.forward(50)
my_turtle = turtle.pencolor("red")
my_turtle = turtle.penup()
my_turtle = turtle.forward(10)
my_turtle = turtle.pendown()
my_turtle = turtle.forward(50)
my_turtle = turtle.left(90)
my_turtle = turtle.forward(50)
my_turtle = turtle.left(90)
my_turtle = turtle.forward(50)
my_turtle = turtle.left(90)
my_turtle = turtle.forward(50)
turtle.exitonclick()